export const APPSUPPLIST_FETCH_REQUEST = 'APPSUPPLIST_FETCH_REQUEST';
export const APPSUPPLIST_FETCH_SUCCESS = 'APPSUPPLIST_FETCH_SUCCESS';
export const APPSUPPLIST_FETCH_FAIL = 'APPSUPPLIST_FETCH_FAIL';
