export const ATTENDANCE_REQUEST = 'ATTENDANCE_REQUEST';
export const ATTENDANCE_FAIL = 'ATTENDANCE_FAIL';
export const ATTENDANCE_FETCH_SUCCESS = 'ATTENDANCE_FETCH_SUCCESS';
export const ATTENDANCE_CREATE_SUCCESS = 'ATTENDANCE_CREATE_SUCCESS';
export const ATTENDANCE_UPDATE_SUCCESS = 'ATTENDANCE_UPDATE_SUCCESS';
export const ATTENDANCE_DELETE_SUCCESS = 'ATTENDANCE_DELETE_SUCCESS';
