export const AUTHORITY_REQUEST = 'AUTHORITY_FETCH_REQUEST';
export const AUTHORITY_FETCH_SUCCESS = 'AUTHORITY_FETCH_SUCCESS';
export const AUTHORITY_CREATE_SUCCESS = 'AUTHORITY_CREATE_SUCCESS';
export const AUTHORITY_UPDATE_SUCCESS = 'AUTHORITY_UPDATE_SUCCESS';
export const AUTHORITY_FAIL = 'AUTHORITY_FETCH_FAIL';
export const AUTHORITY_DELETE_SUCCESS = 'AUTHORITY_DELETE_SUCCESS';
