export const PERSON_REQUEST = 'PERSON_REQUEST';
export const PERSON_FAIL = 'PERSON_FAIL';
export const PERSON_FETCH_SUCCESS = 'PERSON_FETCH_SUCCESS';
export const PERSON_CREATE_SUCCESS = 'PERSON_CREATE_SUCCESS';
export const PERSON_UPDATE_SUCCESS = 'PERSON_UPDATE_SUCCESS';
export const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
