export const CONTRACT_REVIEW_REQUEST = 'CONTRACT_REVIEW_FETCH_REQUEST';
export const CONTRACT_REVIEW_FETCH_SUCCESS = 'CONTRACT_REVIEW_FETCH_SUCCESS';
export const CONTRACT_REVIEW_CREATE_SUCCESS = 'CONTRACT_REVIEW_CREATE_SUCCESS';
export const CONTRACT_REVIEW_UPDATE_SUCCESS = 'CONTRACT_REVIEW_UPDATE_SUCCESS';
export const CONTRACT_REVIEW_FAIL = 'CONTRACT_REVIEW_FETCH_FAIL';
export const CONTRACT_REVIEW_DELETE_SUCCESS = 'CONTRACT_REVIEW_DELETE_SUCCESS';
