export const COMP_CRITERIA_FETCH_REQUEST = 'COMP_CRITERIA_FETCH_REQUEST';
export const COMP_CRITERIA_FETCH_SUCCESS = 'COMP_CRITERIA_FETCH_SUCCESS';
export const COMP_CRITERIA_FETCH_FAIL = 'COMP_CRITERIA_FETCH_FAIL';