export const CUSTOMER_FEEDBACK_REQUEST = 'CUSTOMER_FEEDBACK_FETCH_REQUEST';
export const CUSTOMER_FEEDBACK_FETCH_SUCCESS =
	'CUSTOMER_FEEDBACK_FETCH_SUCCESS';
export const CUSTOMER_FEEDBACK_CREATE_SUCCESS =
	'CUSTOMER_FEEDBACK_CREATE_SUCCESS';
export const CUSTOMER_FEEDBACK_UPDATE_SUCCESS =
	'CUSTOMER_FEEDBACK_UPDATE_SUCCESS';
export const CUSTOMER_FEEDBACK_FAIL = 'CUSTOMER_FEEDBACK_FETCH_FAIL';
export const CUSTOMER_FEEDBACK_DELETE_SUCCESS =
	'CUSTOMER_FEEDBACK_DELETE_SUCCESS';
