export const CUSTOMER_COMPLAINT_REQUEST = 'CUSTOMER_COMPLAINT_FETCH_REQUEST';
export const CUSTOMER_COMPLAINT_FETCH_SUCCESS =
	'CUSTOMER_COMPLAINT_FETCH_SUCCESS';
export const CUSTOMER_COMPLAINT_CREATE_SUCCESS =
	'CUSTOMER_COMPLAINT_CREATE_SUCCESS';
export const CUSTOMER_COMPLAINT_UPDATE_SUCCESS =
	'CUSTOMER_COMPLAINT_UPDATE_SUCCESS';
export const CUSTOMER_COMPLAINT_FAIL = 'CUSTOMER_COMPLAINT_FETCH_FAIL';
export const CUSTOMER_COMPLAINT_DELETE_SUCCESS =
	'CUSTOMER_COMPLAINT_DELETE_SUCCESS';
