export const DELIVERY_ORDER_REQUEST = 'DELIVERY_ORDER_FETCH_REQUEST';
export const DELIVERY_ORDER_FETCH_SUCCESS = 'DELIVERY_ORDER_FETCH_SUCCESS';
export const DELIVERY_ORDER_CREATE_SUCCESS = 'DELIVERY_ORDER_CREATE_SUCCESS';
export const DELIVERY_ORDER_UPDATE_SUCCESS = 'DELIVERY_ORDER_UPDATE_SUCCESS';
export const DELIVERY_ORDER_FAIL = 'DELIVERY_ORDER_FETCH_FAIL';
export const DELIVERY_ORDER_DELETE_SUCCESS = 'DELIVERY_ORDER_DELETE_SUCCESS';
