export const DEPARTMENT_REQUEST = 'DEPARTMENT_REQUEST';
export const DEPARTMENT_FAIL = 'DEPARTMENT_FAIL';
export const DEPARTMENT_FETCH_SUCCESS = 'DEPARTMENT_FETCH_SUCCESS';
export const DEPARTMENT_CREATE_SUCCESS = 'DEPARTMENT_CREATE_SUCCESS';
export const DEPARTMENT_UPDATE_SUCCESS = 'DEPARTMENT_UPDATE_SUCCESS';
export const DEPARTMENT_DELETE_SUCCESS = 'DEPARTMENT_DELETE_SUCCESS';