export const DESIGNATION_REQUEST = 'DESIGNATION_REQUEST';
export const DESIGNATION_FETCH_SUCCESS = 'DESIGNATION_FETCH_SUCCESS';
export const DESIGNATION_CREATE_SUCCESS = 'DESIGNATION_CREATE_SUCCESS';
export const DESIGNATION_UPDATE_SUCCESS = 'DESIGNATION_UPDATE_SUCCESS';
export const DESIGNATION_DELETE_SUCCESS = 'DESIGNATION_DELETE_SUCCESS';
export const DESIGNATION_FAIL = 'DESIGNATION_FAIL';
