export const DESIGNATION_FETCH_REQUEST = 'DESIGNATION_FETCH_REQUEST';
export const DESIGNATION_FETCH_SUCCESS = 'DESIGNATION_FETCH_SUCCESS';
export const DESIGNATION_FETCH_FAIL = 'DESIGNATION_FETCH_FAIL';