export const EDUCATION_REQUEST = 'EDUCATION_REQUEST';
export const EDUCATION_FAIL = 'EDUCATION_FAIL';
export const EDUCATION_FETCH_SUCCESS = 'EDUCATION_FETCH_SUCCESS';
export const EDUCATION_CREATE_SUCCESS = 'EDUCATION_CREATE_SUCCESS';
export const EDUCATION_UPDATE_SUCCESS = 'EDUCATION_UPDATE_SUCCESS';
export const EDUCATION_DELETE_SUCCESS = 'EDUCATION_DELETE_SUCCESS';
