export const EMPLOYEE_REQUEST = 'EMPLOYEE_REQUEST';
export const EMPLOYEE_FAIL = 'EMPLOYEE_FAIL';
export const EMPLOYEE_FETCH_SUCCESS = 'EMPLOYEE_FETCH_SUCCESS';
export const EMPLOYEE_SINGLE_FETCH_SUCCESS = 'EMPLOYEE_SINGLE_FETCH_SUCCESS';
export const EMPLOYEE_UNHIRED_FETCH_SUCCESS = 'EMPLOYEE_UNHIRED_FETCH_SUCCESS';
export const EMPLOYEE_CREATE_SUCCESS = 'EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_UPDATE_SUCCESS = 'EMPLOYEE_UPDATE_SUCCESS';
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS';
