export const EXECRAT_REQUEST = 'EXECRAT_REQUEST';
export const EXECRAT_FAIL = 'EXECRAT_FAIL';
export const EXECRAT_FETCH_SUCCESS = 'EXECRAT_FETCH_SUCCESS';
export const EXECRAT_CREATE_SUCCESS = 'EXECRAT_CREATE_SUCCESS';
export const EXECRAT_UPDATE_SUCCESS = 'EXECRAT_UPDATE_SUCCESS';
export const EXECRAT_DELETE_SUCCESS = 'EXECRAT_DELETE_SUCCESS';
