export const EXECPERFORMANCE_REQUEST = 'EXECPERFORMANCE_REQUEST';
export const EXECPERFORMANCE_FAIL = 'EXECPERFORMANCE_FAIL';
export const EXECPERFORMANCE_FETCH_SUCCESS = 'EXECPERFORMANCE_FETCH_SUCCESS';
export const EXECPERFORMANCE_CREATE_SUCCESS = 'EXECPERFORMANCE_CREATE_SUCCESS';
export const EXECPERFORMANCE_UPDATE_SUCCESS = 'EXECPERFORMANCE_UPDATE_SUCCESS';
export const EXECPERFORMANCE_DELETE_SUCCESS = 'EXECPERFORMANCE_DELETE_SUCCESS';
