export const EXECPREREQ_REQUEST = 'EXECPREREQ_REQUEST';
export const EXECPREREQ_FAIL = 'EXECPREREQ_FAIL';
export const EXECPREREQ_FETCH_SUCCESS = 'EXECPREREQ_FETCH_SUCCESS';
export const EXECPREREQ_CREATE_SUCCESS = 'EXECPREREQ_CREATE_SUCCESS';
export const EXECPREREQ_UPDATE_SUCCESS = 'EXECPREREQ_UPDATE_SUCCESS';
export const EXECPREREQ_DELETE_SUCCESS = 'EXECPREREQ_DELETE_SUCCESS';
