export const EXPERIENCE_REQUEST = 'EXPERIENCE_REQUEST';
export const EXPERIENCE_FAIL = 'EXPERIENCE_FAIL';
export const EXPERIENCE_FETCH_SUCCESS = 'EXPERIENCE_FETCH_SUCCESS';
export const EXPERIENCE_CREATE_SUCCESS = 'EXPERIENCE_CREATE_SUCCESS';
export const EXPERIENCE_UPDATE_SUCCESS = 'EXPERIENCE_UPDATE_SUCCESS';
export const EXPERIENCE_DELETE_SUCCESS = 'EXPERIENCE_DELETE_SUCCESS';
