export const INWARD_REQUEST = "INWARD_FETCH_REQUEST";
export const INWARD_FETCH_SUCCESS = "INWARD_FETCH_SUCCESS";
export const INWARD_CREATE_SUCCESS = "INWARD_CREATE_SUCCESS";
export const INWARD_UPDATE_SUCCESS = "INWARD_UPDATE_SUCCESS";
export const INWARD_FAIL = "INWARD_FETCH_FAIL";
export const INWARD_DELETE_SUCCESS = "INWARD_DELETE_SUCCESS";
