export const INWARDAPPROVAL_REQUEST = "INWARDAPPROVAL_FETCH_REQUEST";
export const INWARDAPPROVAL_FETCH_SUCCESS = "INWARDAPPROVAL_FETCH_SUCCESS";
export const INWARDAPPROVAL_CREATE_SUCCESS = "INWARDAPPROVAL_CREATE_SUCCESS";
export const INWARDAPPROVAL_UPDATE_SUCCESS = "INWARDAPPROVAL_UPDATE_SUCCESS";
export const INWARDAPPROVAL_FAIL = "INWARDAPPROVAL_FETCH_FAIL";
export const INWARDAPPROVAL_DELETE_SUCCESS = "INWARDAPPROVAL_DELETE_SUCCESS";
