export const INWARD_GATE_PASS_REQUEST = "INWARD_GATE_PASS_FETCH_REQUEST";
export const INWARD_GATE_PASS_FETCH_SUCCESS = "INWARD_GATE_PASS_FETCH_SUCCESS";
export const INWARD_GATE_PASS_CREATE_SUCCESS = "INWARD_GATE_PASS_CREATE_SUCCESS";
export const INWARD_GATE_PASS_UPDATE_SUCCESS = "INWARD_GATE_PASS_UPDATE_SUCCESS";
export const INWARD_GATE_PASS_FAIL = "INWARD_GATE_PASS_FETCH_FAIL";
export const INWARD_GATE_PASS_DELETE_SUCCESS = "INWARD_GATE_PASS_DELETE_SUCCESS";