export const JOB_DESCRIPTION_REQUEST = 'JOB_DESCRIPTION_FETCH_REQUEST';
export const JOB_DESCRIPTION_FETCH_SUCCESS = 'JOB_DESCRIPTION_FETCH_SUCCESS';
export const JOB_DESCRIPTION_CREATE_SUCCESS = 'JOB_DESCRIPTION_CREATE_SUCCESS';
export const JOB_DESCRIPTION_UPDATE_SUCCESS = 'JOB_DESCRIPTION_UPDATE_SUCCESS';
export const JOB_DESCRIPTION_FAIL = 'JOB_DESCRIPTION_FETCH_FAIL';
export const JOB_DESCRIPTION_DELETE_SUCCESS = 'JOB_DESCRIPTION_DELETE_SUCCESS';
