export const LEAVE_REQUEST = 'LEAVE_REQUEST';
export const LEAVE_FAIL = 'LEAVE_FAIL';
export const LEAVE_FETCH_SUCCESS = 'LEAVE_FETCH_SUCCESS';
export const LEAVE_CREATE_SUCCESS = 'LEAVE_CREATE_SUCCESS';
export const LEAVE_UPDATE_SUCCESS = 'LEAVE_UPDATE_SUCCESS';
export const LEAVE_DELETE_SUCCESS = 'LEAVE_DELETE_SUCCESS';
