export const MATERIAL_FETCH_REQUEST = 'MATERIAL_FETCH_REQUEST';
export const MATERIAL_FETCH_SUCCESS = 'MATERIAL_FETCH_SUCCESS';
export const MATERIAL_FETCH_FAIL = 'MATERIAL_FETCH_FAIL';

export const SPEC_CAT_MATERIAL_FETCH_REQUEST = 'SPEC_CAT_MATERIAL_FETCH_REQUEST';
export const SPEC_CAT_MATERIAL_FETCH_SUCCESS = 'SPEC_CAT_MATERIAL_FETCH_SUCCESS';
export const SPEC_CAT_MATERIAL_FETCH_FAIL = 'SPEC_CAT_MATERIAL_FETCH_FAIL';