export const MATERIAL_REQUEST = 'MATERIAL_REQUEST';
export const MATERIAL_FAIL = 'MATERIAL_FAIL';
export const MATERIAL_FETCH_SUCCESS = 'MATERIAL_FETCH_SUCCESS';
export const MATERIAL_CREATE_SUCCESS = 'MATERIAL_CREATE_SUCCESS';
export const MATERIAL_UPDATE_SUCCESS = 'MATERIAL_UPDATE_SUCCESS';
export const MATERIAL_DELETE_SUCCESS = 'MATERIAL_DELETE_SUCCESS';
