export const NONEXTPERFORMANCE_REQUEST = 'NONEXTPERFORMANCE_REQUEST';
export const NONEXTPERFORMANCE_FAIL = 'NONEXTPERFORMANCE_FAIL';
export const NONEXTPERFORMANCE_FETCH_SUCCESS =
	'NONEXTPERFORMANCE_FETCH_SUCCESS';
export const NONEXTPERFORMANCE_CREATE_SUCCESS =
	'NONEXTPERFORMANCE_CREATE_SUCCESS';
export const NONEXTPERFORMANCE_UPDATE_SUCCESS =
	'NONEXTPERFORMANCE_UPDATE_SUCCESS';
export const NONEXTPERFORMANCE_DELETE_SUCCESS =
	'NONEXTPERFORMANCE_DELETE_SUCCESS';
