export const NONEXECRAT_REQUEST = 'NONEXECRAT_REQUEST';
export const NONEXECRAT_FAIL = 'NONEXECRAT_FAIL';
export const NONEXECRAT_FETCH_SUCCESS = 'NONEXECRAT_FETCH_SUCCESS';
export const NONEXECRAT_CREATE_SUCCESS = 'NONEXECRAT_CREATE_SUCCESS';
export const NONEXECRAT_UPDATE_SUCCESS = 'NONEXECRAT_UPDATE_SUCCESS';
export const NONEXECRAT_DELETE_SUCCESS = 'NONEXECRAT_DELETE_SUCCESS';
