export const NONEXECPREREQ_REQUEST = 'NONEXECPREREQ_REQUEST';
export const NONEXECPREREQ_FAIL = 'NONEXECPREREQ_FAIL';
export const NONEXECPREREQ_FETCH_SUCCESS = 'NONEXECPREREQ_FETCH_SUCCESS';
export const NONEXECPREREQ_CREATE_SUCCESS = 'NONEXECPREREQ_CREATE_SUCCESS';
export const NONEXECPREREQ_UPDATE_SUCCESS = 'NONEXECPREREQ_UPDATE_SUCCESS';
export const NONEXECPREREQ_DELETE_SUCCESS = 'NONEXECPREREQ_DELETE_SUCCESS';
