export const PURCHASE_ORDER_FETCH_REQUEST = 'PURCHASE_ORDER_FETCH_REQUEST';
export const PURCHASE_ORDER_FETCH_SUCCESS = 'PURCHASE_ORDER_FETCH_SUCCESS';
export const PURCHASE_ORDER_FETCH_FAIL = 'PURCHASE_ORDER_FETCH_FAIL';

export const SINGLE_PURCHASE_ORDER_FETCH_REQUEST = 'SINGLE_PURCHASE_ORDER_FETCH_REQUEST';
export const SINGLE_PURCHASE_ORDER_FETCH_SUCCESS = 'SINGLE_PURCHASE_ORDER_FETCH_SUCCESS';
export const SINGLE_PURCHASE_ORDER_FETCH_FAIL = 'SINGLE_PURCHASE_ORDER_FETCH_FAIL';

export const INSPECTED_ORDER_FETCH_REQUEST = 'INSPECTED_ORDER_FETCH_REQUEST';
export const INSPECTED_ORDER_FETCH_SUCCESS = 'INSPECTED_ORDER_FETCH_SUCCESS';
export const INSPECTED_ORDER_FETCH_FAIL = 'INSPECTED_ORDER_FETCH_FAIL';