export const ORDER_BOOKING_REQUEST = 'ORDER_BOOKING_FETCH_REQUEST';
export const ORDER_BOOKING_FETCH_SUCCESS = 'ORDER_BOOKING_FETCH_SUCCESS';
export const ORDER_BOOKING_CREATE_SUCCESS = 'ORDER_BOOKING_CREATE_SUCCESS';
export const ORDER_BOOKING_UPDATE_SUCCESS = 'ORDER_BOOKING_UPDATE_SUCCESS';
export const ORDER_BOOKING_FAIL = 'ORDER_BOOKING_FETCH_FAIL';
export const ORDER_BOOKING_DELETE_SUCCESS = 'ORDER_BOOKING_DELETE_SUCCESS';