export const PURCHASE_ORDER_REQUEST = 'PURCHASE_ORDER_FETCH_REQUEST';
export const PURCHASE_ORDER_FETCH_SUCCESS = 'PURCHASE_ORDER_FETCH_SUCCESS';
export const PURCHASE_ORDER_CREATE_SUCCESS = 'PURCHASE_ORDER_FETCH_SUCCESS';
export const PURCHASE_ORDER_UPDATE_SUCCESS = 'PURCHASE_ORDER_FETCH_SUCCESS';
export const PURCHASE_ORDER_FAIL = 'PURCHASE_ORDER_FETCH_FAIL';
export const PURCHASE_ORDER_SINGLE_FETCH_SUCCESS =
	'PURCHASE_ORDER_SINGLE_FETCH_SUCCESS';
