export const OUTWARD_GATE_PASS_REQUEST = "OUTWARD_GATE_PASS_FETCH_REQUEST";
export const OUTWARD_GATE_PASS_FETCH_SUCCESS = "OUTWARD_GATE_PASS_FETCH_SUCCESS";
export const OUTWARD_GATE_PASS_CREATE_SUCCESS = "OUTWARD_GATE_PASS_CREATE_SUCCESS";
export const OUTWARD_GATE_PASS_UPDATE_SUCCESS = "OUTWARD_GATE_PASS_UPDATE_SUCCESS";
export const OUTWARD_GATE_PASS_FAIL = "OUTWARD_GATE_PASS_FETCH_FAIL";
export const OUTWARD_GATE_PASS_DELETE_SUCCESS = "OUTWARD_GATE_PASS_DELETE_SUCCESS";