export const PRODUCTION_REPORT_FETCH_REQUEST =
	'PRODUCTION_REPORT_FETCH_REQUEST';
export const PRODUCTION_REPORT_FETCH_SUCCESS =
	'PRODUCTION_REPORT_FETCH_SUCCESS';
export const PRODUCTION_REPORT_FETCH_FAIL = 'PRODUCTION_REPORT_FETCH_FAIL';
