export const REQ_FETCH_REQUEST = 'REQ_FETCH_REQUEST';
export const REQ_FETCH_SUCCESS = 'REQ_FETCH_SUCCESS';
export const REQ_FETCH_FAIL = 'REQ_FETCH_FAIL';

export const SINGLE_REQ_FETCH_REQUEST = 'SINGLE_REQ_FETCH_REQUEST';
export const SINGLE_REQ_FETCH_SUCCESS = 'SINGLE_REQ_FETCH_SUCCESS';
export const SINGLE_REQ_FETCH_FAIL = 'SINGLE_REQ_FETCH_FAIL';

