export const PURCHASE_REQ_REQUEST = 'PURCHASE_REQ_FETCH_REQUEST';
export const PURCHASE_REQ_FETCH_SUCCESS = 'PURCHASE_REQ_FETCH_SUCCESS';
export const PURCHASE_REQ_CREATE_SUCCESS = 'PURCHASE_REQ_CREATE_SUCCESS';
export const PURCHASE_REQ_UPDATE_SUCCESS = 'PURCHASE_REQ_UPDATE_SUCCESS';
export const PURCHASE_REQ_FAIL = 'PURCHASE_REQ_FETCH_FAIL';
