export const RESPONSIBILITY_REQUEST = 'RESPONSIBILITY_FETCH_REQUEST';
export const RESPONSIBILITY_FETCH_SUCCESS = 'RESPONSIBILITY_FETCH_SUCCESS';
export const RESPONSIBILITY_CREATE_SUCCESS = 'RESPONSIBILITY_CREATE_SUCCESS';
export const RESPONSIBILITY_UPDATE_SUCCESS = 'RESPONSIBILITY_UPDATE_SUCCESS';
export const RESPONSIBILITY_FAIL = 'RESPONSIBILITY_FETCH_FAIL';
export const RESPONSIBILITY_DELETE_SUCCESS = 'RESPONSIBILITY_DELETE_SUCCESS';
