export const SALARY_REQUEST = 'SALARY_REQUEST';
export const SALARY_FAIL = 'SALARY_FAIL';
export const SALARY_FETCH_SUCCESS = 'SALARY_FETCH_SUCCESS';
export const SALARY_CREATE_SUCCESS = 'SALARY_CREATE_SUCCESS';
export const SALARY_UPDATE_SUCCESS = 'SALARY_UPDATE_SUCCESS';
export const SALARY_DELETE_SUCCESS = 'SALARY_DELETE_SUCCESS';
