export const SALES_CONTRACT_REQUEST = 'SALES_CONTRACT_FETCH_REQUEST';
export const SALES_CONTRACT_FETCH_SUCCESS = 'SALES_CONTRACT_FETCH_SUCCESS';
export const SALES_CONTRACT_CREATE_SUCCESS = 'SALES_CONTRACT_CREATE_SUCCESS';
export const SALES_CONTRACT_UPDATE_SUCCESS = 'SALES_CONTRACT_UPDATE_SUCCESS';
export const SALES_CONTRACT_FAIL = 'SALES_CONTRACT_FETCH_FAIL';
export const SALES_CONTRACT_DELETE_SUCCESS = 'SALES_CONTRACT_DELETE_SUCCESS';
