export const SKILL_REQUEST = 'SKILL_REQUEST';
export const SKILL_FAIL = 'SKILL_FAIL';
export const SKILL_FETCH_SUCCESS = 'SKILL_FETCH_SUCCESS';
export const SKILL_CREATE_SUCCESS = 'SKILL_CREATE_SUCCESS';
export const SKILL_UPDATE_SUCCESS = 'SKILL_UPDATE_SUCCESS';
export const SKILL_DELETE_SUCCESS = 'SKILL_DELETE_SUCCESS';
