export const STORE_CATEGORY_REQUEST = 'STORE_CATEGORY_REQUEST';
export const STORE_CATEGORY_FAIL = 'STORE_CATEGORY_FAIL';
export const STORE_CATEGORY_FETCH_SUCCESS = 'STORE_CATEGORY_FETCH_SUCCESS';
export const STORE_CATEGORY_CREATE_SUCCESS = 'STORE_CATEGORY_CREATE_SUCCESS';
export const STORE_CATEGORY_UPDATE_SUCCESS = 'STORE_CATEGORY_UPDATE_SUCCESS';
export const STORE_CATEGORY_DELETE_SUCCESS = 'STORE_CATEGORY_DELETE_SUCCESS';
