export const SUB_CATEGORY_REQUEST = 'SUB_CATEGORY_FETCH_REQUEST';
export const SUB_CATEGORY_FETCH_SUCCESS = 'SUB_CATEGORY_FETCH_SUCCESS';
export const SUB_CATEGORY_CREATE_SUCCESS = 'SUB_CATEGORY_CREATE_SUCCESS';
export const SUB_CATEGORY_UPDATE_SUCCESS = 'SUB_CATEGORY_UPDATE_SUCCESS';
export const SUB_CATEGORY_FAIL = 'SUB_CATEGORY_FETCH_FAIL';
export const SUB_CATEGORY_DELETE_SUCCESS = 'SUB_CATEGORY_DELETE_SUCCESS';
