export const TRAININGVENUE_REQUEST = 'TRAININGVENUE_REQUEST';
export const TRAININGVENUE_FAIL = 'TRAININGVENUE_FAIL';
export const TRAININGVENUE_FETCH_SUCCESS = 'TRAININGVENUE_FETCH_SUCCESS';
export const TRAININGVENUE_CREATE_SUCCESS = 'TRAININGVENUE_CREATE_SUCCESS';
export const TRAININGVENUE_UPDATE_SUCCESS = 'TRAININGVENUE_UPDATE_SUCCESS';
export const TRAININGVENUE_DELETE_SUCCESS = 'TRAININGVENUE_DELETE_SUCCESS';
