export const TRAININGPREREQ_REQUEST = 'TRAININGPREREQ_REQUEST';
export const TRAININGPREREQ_FAIL = 'TRAININGPREREQ_FAIL';
export const TRAININGPREREQ_FETCH_SUCCESS = 'TRAININGPREREQ_FETCH_SUCCESS';
export const TRAININGPREREQ_CREATE_SUCCESS = 'TRAININGPREREQ_CREATE_SUCCESS';
export const TRAININGPREREQ_UPDATE_SUCCESS = 'TRAININGPREREQ_UPDATE_SUCCESS';
export const TRAININGPREREQ_DELETE_SUCCESS = 'TRAININGPREREQ_DELETE_SUCCESS';
