export const TRAINING_EVALUATION_REQUEST = 'TRAINING_EVALUATION_REQUEST';
export const TRAINING_EVALUATION_FAIL = 'TRAINING_EVALUATION_FAIL';
export const TRAINING_EVALUATION_FETCH_SUCCESS =
	'TRAINING_EVALUATION_FETCH_SUCCESS';
export const TRAINING_EVALUATION_CREATE_SUCCESS =
	'TRAINING_EVALUATION_CREATE_SUCCESS';
export const TRAINING_EVALUATION_UPDATE_SUCCESS =
	'TRAINING_EVALUATION_UPDATE_SUCCESS';
export const TRAINING_EVALUATION_DELETE_SUCCESS =
	'TRAINING_EVALUATION_DELETE_SUCCESS';
