export const TRAININGATTENDANCE_REQUEST = 'TRAININGATTENDANCE_REQUEST';
export const TRAININGATTENDANCE_FAIL = 'TRAININGATTENDANCE_FAIL';
export const TRAININGATTENDANCE_FETCH_SUCCESS =
	'TRAININGATTENDANCE_FETCH_SUCCESS';
export const TRAININGATTENDANCE_CREATE_SUCCESS =
	'TRAININGATTENDANCE_CREATE_SUCCESS';
export const TRAININGATTENDANCE_UPDATE_SUCCESS =
	'TRAININGATTENDANCE_UPDATE_SUCCESS';
export const TRAININGATTENDANCE_DELETE_SUCCESS =
	'TRAININGATTENDANCE_DELETE_SUCCESS';
