export const TRAININGNEEDIDENTIFICATION_REQUEST =
	'TRAININGNEEDIDENTIFICATION_REQUEST';
export const TRAININGNEEDIDENTIFICATION_FAIL =
	'TRAININGNEEDIDENTIFICATION_FAIL';
export const TRAININGNEEDIDENTIFICATION_FETCH_SUCCESS =
	'TRAININGNEEDIDENTIFICATION_FETCH_SUCCESS';
export const TRAININGNEEDIDENTIFICATION_CREATE_SUCCESS =
	'TRAININGNEEDIDENTIFICATION_CREATE_SUCCESS';
export const TRAININGNEEDIDENTIFICATION_UPDATE_SUCCESS =
	'TRAININGNEEDIDENTIFICATION_UPDATE_SUCCESS';
export const TRAININGNEEDIDENTIFICATION_DELETE_SUCCESS =
	'TRAININGNEEDIDENTIFICATION_DELETE_SUCCESS';
