export const TRAINING_REQUEST = 'TRAINING_REQUEST';
export const TRAINING_FAIL = 'TRAINING_FAIL';
export const TRAINING_FETCH_SUCCESS = 'TRAINING_FETCH_SUCCESS';
export const TRAINING_CREATE_SUCCESS = 'TRAINING_CREATE_SUCCESS';
export const TRAINING_UPDATE_SUCCESS = 'TRAINING_UPDATE_SUCCESS';
export const TRAINING_DELETE_SUCCESS = 'TRAINING_DELETE_SUCCESS';
