export const TRAININGPLAN_REQUEST = 'TRAININGPLAN_REQUEST';
export const TRAININGPLAN_FAIL = 'TRAININGPLAN_FAIL';
export const TRAININGPLAN_FETCH_SUCCESS = 'TRAININGPLAN_FETCH_SUCCESS';
export const TRAININGPLAN_CREATE_SUCCESS = 'TRAININGPLAN_CREATE_SUCCESS';
export const TRAININGPLAN_UPDATE_SUCCESS = 'TRAININGPLAN_UPDATE_SUCCESS';
export const TRAININGPLAN_DELETE_SUCCESS = 'TRAININGPLAN_DELETE_SUCCESS';
