export const UNIT_REQUEST = 'UNIT_FETCH_REQUEST';
export const UNIT_FETCH_SUCCESS = 'UNIT_FETCH_SUCCESS';
export const UNIT_CREATE_SUCCESS = 'UNIT_CREATE_SUCCESS';
export const UNIT_UPDATE_SUCCESS = 'UNIT_UPDATE_SUCCESS';
export const UNIT_FAIL = 'UNIT_FETCH_FAIL';
export const UNIT_DELETE_SUCCESS = 'UNIT_DELETE_SUCCESS';
