export const USER_REQUEST = 'USER_REQUEST';
export const USER_FAIL = 'USER_FAIL';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
