export const VEHICLE_REQUEST = 'VEHICLE_FETCH_REQUEST';
export const VEHICLE_FETCH_SUCCESS = 'VEHICLE_FETCH_SUCCESS';
export const VEHICLE_CREATE_SUCCESS = 'VEHICLE_CREATE_SUCCESS';
export const VEHICLE_UPDATE_SUCCESS = 'VEHICLE_UPDATE_SUCCESS';
export const VEHICLE_FAIL = 'VEHICLE_FETCH_FAIL';
export const VEHICLE_DELETE_SUCCESS = 'VEHICLE_DELETE_SUCCESS';
