export const VENDOR_REQUEST = 'VENDOR_REQUEST';
export const VENDOR_FAIL = 'VENDOR_FAIL';
export const VENDOR_FETCH_SUCCESS = 'VENDOR_FETCH_SUCCESS';
export const VENDOR_CREATE_SUCCESS = 'VENDOR_CREATE_SUCCESS';
export const VENDOR_UPDATE_SUCCESS = 'VENDOR_UPDATE_SUCCESS';
export const VENDOR_DELETE_SUCCESS = 'VENDOR_DELETE_SUCCESS';
