export const VENDOR_FETCH_REQUEST = 'VENDOR_FETCH_REQUEST';
export const VENDOR_FETCH_SUCCESS = 'VENDOR_FETCH_SUCCESS';
export const VENDOR_FETCH_FAIL = 'VENDOR_FETCH_FAIL';

export const NON_VERIFY_VENDOR_FETCH_REQUEST = 'NON_VERIFY_VENDOR_FETCH_REQUEST';
export const NON_VERIFY_VENDOR_FETCH_SUCCESS = 'NON_VERIFY_VENDOR_FETCH_SUCCESS';
export const NON_VERIFY_VENDOR_FETCH_FAIL = 'NON_VERIFY_VENDOR_FETCH_FAIL';