export const VOUCHER_REQUEST = 'VOUCHER_FETCH_REQUEST';
export const VOUCHER_FETCH_SUCCESS = 'VOUCHER_FETCH_SUCCESS';
export const VOUCHER_CREATE_SUCCESS = 'VOUCHER_CREATE_SUCCESS';
export const VOUCHER_UPDATE_SUCCESS = 'VOUCHER_UPDATE_SUCCESS';
export const VOUCHER_FAIL = 'VOUCHER_FETCH_FAIL';
export const VOUCHER_DELETE_SUCCESS = 'VOUCHER_DELETE_SUCCESS';
